name: 自动部署
# 当有改动推送到master分支时，启动Action
# 教程文档 https://zhsher.cn/posts/8779/#4-3-%E6%96%B9%E6%A1%88%E4%B8%89
on:
  push:
    branches:
      - main
      # 2020年10月后github新建仓库默认分支改为main，注意更改

jobs: # 工作流
  deploy: # 自定义名称
    runs-on: ubuntu-latest  # 运行在虚拟机环境
    steps:
      - name: 1. 拉取代码  
        uses: actions/checkout@v3

      - name: 2. 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: 5. 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install -g pnpm
          pnpm install

      - name: 6. 生成静态文件
        run: |
          pnpm build

      # - name: 7. 部署到Github
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     token: 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
      #     repository-name: Pupper0601/Pupper0601.github.io
      #     branch: main
      #     folder: public
      #     clean-exclude: |
      #       public/.github
      #     commit-message: "${{ github.event.head_commit.message }} 由Github Actions更新"

      - name: 8. 推送到服务器私有仓库 #没有使用服务器可删除该步骤
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_ACCESS_TOKEN }} #服务器生成的私钥，例如 -----BEGIN RSA PRIVATE KEY-----xxxx-----END RSA PRIVATE KEY-----
          ARGS: "-rltgoDzvO --delete" # rsync参数
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }} #服务器ip地址，例如 1.2.3.4
          REMOTE_USER: ${{ secrets.SERVER_USER }} #登录用户，例如 root
          TARGET: /www/wwwroot/home.pupper.cn  # ${{ secrets.SERVER_TARGET }}    #服务器目录，例如 /www/blog.panghai.top
          EXCLUDE: ".git/,.user.ini"
